

ENV_VAR_LOGGING_MODE = 'AUDIOCARDS_LOGGING_MODE'
ENV_VAR_LOGGING_FILE = 'AUDIOCARDS_LOGGING_FILE'
ENV_VAR_LOGGING_LEVEL = 'AUDIOCARDS_LOGGING_LEVEL'

LOGGER_NAME = 'audiocards'
LOGGER_NAME_TEST = 'test_audiocards'